### ISSUE TITLE
Issue about whitelist/multiple directory coverage zero

### ISSUE THREAD

**Issue by afbora** [krakjoe/pcov#34]
Coverage always `0.00%` files for `./config` directory even if `dpcov.directory` option used

This is a bug or am i missing something? 🤔 

**.travis.yml**

````yaml
install:
   ...
  - composer require --no-interaction --ignore-platform-reqs "phpunit/phpunit:^7" "friendsofphp/php-cs-fixer" "pcov/clobber"
   ...

script:
    php -dpcov.enabled=1 -dpcov.directory=./config ./src ./vendor/bin/pcov clobber; ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

````

Also tried

````yaml
script:
  - php -dpcov.directory=. -dpcov.exclude="~vendor~" ./vendor/bin/pcov clobber; ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

````

**phpunit.xml.dist**

````xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
    bootstrap="tests/bootstrap.php"
    convertErrorsToExceptions="true"
    convertNoticesToExceptions="true"
    convertWarningsToExceptions="true"
    stopOnFailure="true"
    stderr="true"
    colors="true"
    verbose="true">

    <filter>
        <whitelist>
            <directory>./config</directory>
            <directory>./src</directory>
        </whitelist>
    </filter>

    <testsuites>
        <testsuite name="Classes">
            <directory>./tests/</directory>
        </testsuite>
    </testsuites>
</phpunit>
````
